using System.Collections.Generic;
using System.Threading.Tasks;
using USTGlobal.PIP.ApplicationCore.DTOs;

namespace USTGlobal.PIP.ApplicationCore.Interfaces
{
    public interface IProjectHeaderService
    {
        Task<ProjectHeaderCurrencyDTO> GetProjectHeaderData(int projectId, int pipSheetId);
        Task<RouteParamDTO> SaveProjectHeaderData(string userName, ProjectHeaderDTO projectHeader);
        Task<CurrencyDTO> GetCurrencyConversionData(int countryId);
        Task<WorkflowStatusAndAccountSpecificRoleDTO> GetWorkflowStatusAccountRole(string userName, int pipSheetId, int accountId, int projectId = 0);
        Task<RoleAndAccountMainDTO> GetUserRoleForAllAccounts(string userName);
        Task<string> GetAutoGeneratedProjectId(int accountId, string accountCode);
        Task<List<ProjectDTO>> GetProjectsByAccountId(int accountId);
    }
}
